greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_susu_bigquery:
      type: bigquery
      method: service-account
      project: deb2-17aug2023
      dataset: dbt_susu
      threads: 1
      keyfile: deb2-analytics-with-dbt-17aug2023-e3e6a300bd66.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: deb2-17aug2023
      dataset: dbt_susu
      threads: 1
      keyfile: deb2-analytics-with-dbt-17aug2023-e3e6a300bd66.json
      location: asia-southeast1

  target: dbt_susu_bigquery